// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.17.3
// source: getBestStores.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户的经纬度构成的位置
	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getBestStores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_getBestStores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_getBestStores_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type OutletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//用户的请求，包括用户的id，位置，需要返回的店铺数目以及城市id
	UserId  int64     `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pos     *Position `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	ListNum int32     `protobuf:"varint,3,opt,name=listNum,proto3" json:"listNum,omitempty"`
	Method  int32     `protobuf:"varint,4,opt,name=method,proto3" json:"method,omitempty"` // method有1，2，3三个值。1代表按距离召回，2代表按照itemsSold召回，3代表1，2混合。
}

func (x *OutletRequest) Reset() {
	*x = OutletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getBestStores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutletRequest) ProtoMessage() {}

func (x *OutletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getBestStores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutletRequest.ProtoReflect.Descriptor instead.
func (*OutletRequest) Descriptor() ([]byte, []int) {
	return file_getBestStores_proto_rawDescGZIP(), []int{1}
}

func (x *OutletRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OutletRequest) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *OutletRequest) GetListNum() int32 {
	if x != nil {
		return x.ListNum
	}
	return 0
}

func (x *OutletRequest) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

type RetMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//返回的消息结构，包括店铺距离用户的位置，店铺的logoURL，店铺的名字，
	//地址，售出数量
	Distance  string `protobuf:"bytes,1,opt,name=distance,proto3" json:"distance,omitempty"`
	LogoURL   string `protobuf:"bytes,2,opt,name=logoURL,proto3" json:"logoURL,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address   string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ItemsSold string `protobuf:"bytes,5,opt,name=itemsSold,proto3" json:"itemsSold,omitempty"`
}

func (x *RetMessage) Reset() {
	*x = RetMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getBestStores_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetMessage) ProtoMessage() {}

func (x *RetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_getBestStores_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetMessage.ProtoReflect.Descriptor instead.
func (*RetMessage) Descriptor() ([]byte, []int) {
	return file_getBestStores_proto_rawDescGZIP(), []int{2}
}

func (x *RetMessage) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *RetMessage) GetLogoURL() string {
	if x != nil {
		return x.LogoURL
	}
	return ""
}

func (x *RetMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RetMessage) GetItemsSold() string {
	if x != nil {
		return x.ItemsSold
	}
	return ""
}

type OutletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//服务器对请求的返回，包括请求是否成功的状态码，返回的RetMessage的数量以及RetMessage的列表
	Code    int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0表示成功，1表示失败
	ListNum int32         `protobuf:"varint,2,opt,name=listNum,proto3" json:"listNum,omitempty"`
	List    []*RetMessage `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *OutletResponse) Reset() {
	*x = OutletResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getBestStores_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutletResponse) ProtoMessage() {}

func (x *OutletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getBestStores_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutletResponse.ProtoReflect.Descriptor instead.
func (*OutletResponse) Descriptor() ([]byte, []int) {
	return file_getBestStores_proto_rawDescGZIP(), []int{3}
}

func (x *OutletResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OutletResponse) GetListNum() int32 {
	if x != nil {
		return x.ListNum
	}
	return 0
}

func (x *OutletResponse) GetList() []*RetMessage {
	if x != nil {
		return x.List
	}
	return nil
}

var File_getBestStores_proto protoreflect.FileDescriptor

var file_getBestStores_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x65, 0x74, 0x42, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x08,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x22, 0x7c, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x03, 0x70,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c,
	0x6f, 0x67, 0x6f, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f,
	0x67, 0x6f, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x53, 0x6f, 0x6c, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x53, 0x6f, 0x6c,
	0x64, 0x22, 0x65, 0x0a, 0x0e, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x4e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x4e, 0x75,
	0x6d, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x58, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42,
	0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x75,
	0x74, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getBestStores_proto_rawDescOnce sync.Once
	file_getBestStores_proto_rawDescData = file_getBestStores_proto_rawDesc
)

func file_getBestStores_proto_rawDescGZIP() []byte {
	file_getBestStores_proto_rawDescOnce.Do(func() {
		file_getBestStores_proto_rawDescData = protoimpl.X.CompressGZIP(file_getBestStores_proto_rawDescData)
	})
	return file_getBestStores_proto_rawDescData
}

var file_getBestStores_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_getBestStores_proto_goTypes = []interface{}{
	(*Position)(nil),       // 0: proto.Position
	(*OutletRequest)(nil),  // 1: proto.OutletRequest
	(*RetMessage)(nil),     // 2: proto.RetMessage
	(*OutletResponse)(nil), // 3: proto.OutletResponse
}
var file_getBestStores_proto_depIdxs = []int32{
	0, // 0: proto.OutletRequest.pos:type_name -> proto.Position
	2, // 1: proto.OutletResponse.list:type_name -> proto.RetMessage
	1, // 2: proto.GetBestStoresService.GetBestStoresList:input_type -> proto.OutletRequest
	3, // 3: proto.GetBestStoresService.GetBestStoresList:output_type -> proto.OutletResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_getBestStores_proto_init() }
func file_getBestStores_proto_init() {
	if File_getBestStores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getBestStores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getBestStores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getBestStores_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getBestStores_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutletResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getBestStores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getBestStores_proto_goTypes,
		DependencyIndexes: file_getBestStores_proto_depIdxs,
		MessageInfos:      file_getBestStores_proto_msgTypes,
	}.Build()
	File_getBestStores_proto = out.File
	file_getBestStores_proto_rawDesc = nil
	file_getBestStores_proto_goTypes = nil
	file_getBestStores_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetBestStoresServiceClient is the client API for GetBestStoresService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetBestStoresServiceClient interface {
	//
	//获得用户最感兴趣的listNum个店铺
	GetBestStoresList(ctx context.Context, in *OutletRequest, opts ...grpc.CallOption) (*OutletResponse, error)
}

type getBestStoresServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetBestStoresServiceClient(cc grpc.ClientConnInterface) GetBestStoresServiceClient {
	return &getBestStoresServiceClient{cc}
}

func (c *getBestStoresServiceClient) GetBestStoresList(ctx context.Context, in *OutletRequest, opts ...grpc.CallOption) (*OutletResponse, error) {
	out := new(OutletResponse)
	err := c.cc.Invoke(ctx, "/proto.GetBestStoresService/GetBestStoresList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetBestStoresServiceServer is the server API for GetBestStoresService service.
type GetBestStoresServiceServer interface {
	//
	//获得用户最感兴趣的listNum个店铺
	GetBestStoresList(context.Context, *OutletRequest) (*OutletResponse, error)
}

// UnimplementedGetBestStoresServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGetBestStoresServiceServer struct {
}

func (*UnimplementedGetBestStoresServiceServer) GetBestStoresList(context.Context, *OutletRequest) (*OutletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestStoresList not implemented")
}

func RegisterGetBestStoresServiceServer(s *grpc.Server, srv GetBestStoresServiceServer) {
	s.RegisterService(&_GetBestStoresService_serviceDesc, srv)
}

func _GetBestStoresService_GetBestStoresList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetBestStoresServiceServer).GetBestStoresList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GetBestStoresService/GetBestStoresList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetBestStoresServiceServer).GetBestStoresList(ctx, req.(*OutletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetBestStoresService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GetBestStoresService",
	HandlerType: (*GetBestStoresServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBestStoresList",
			Handler:    _GetBestStoresService_GetBestStoresList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getBestStores.proto",
}
